spring.application.name=stayhub-backend

# ===== PostgreSQL =====
spring.datasource.url=jdbc:postgresql://localhost:5432/stayhub
spring.datasource.username=postgres
spring.datasource.password=1011
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=true

# ===== Servidor =====
server.port=8080

# ===== Jackson =====
spring.jackson.serialization.write-dates-as-timestamps=false